name: test-check

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout del código

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm install  # Instalar dependencias

      - name: Run linter
        run: npm run lint  # Ejecutar linter

      - name: Run tests
        run: npm test  # Ejecutar pruebas

      - name: Install CodeClimate test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter  # Descargar e instalar el reporte de test de CodeClimate

      - name: Report to CodeClimate
        run: |
          CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID }} ./cc-test-reporter after-build --exit-code $?
